# local:
@baseUrl = http://localhost:9090
# staging:
# @baseUrl = https://staging.api.algeriastartupjobs.com
# production:
# @baseUrl = http://production.api.algeriastartupjobs.com

GET {{baseUrl}}/posts/feed