# local:
@base_url = http://localhost:9090
# staging:
# @base_url = https://staging.api.algeriastartupjobs.com
# production:
# @base_url = https://production.api.algeriastartupjobs.com
@auth_token = {{confirmLogin.response.body.auth_token}}

###
GET {{base_url}}/posts/feed

###
GET {{base_url}}/posts/0

###
GET {{base_url}}/posts/10

### Non-existing post
GET {{base_url}}/posts/10000

###
GET {{base_url}}/posts/1/similar?per_page=10&page=0

### Non-existing post
GET {{base_url}}/posts/10000/similar?per_page=10&page=0

### Search jobs
GET {{base_url}}/search/posts?query=softare+developer&per_page=10&page=0

### Post count
GET {{base_url}}/posts/count

###
GET {{base_url}}/accounts/by_email?email=test%2Bdeckow-inc.0@algeriastartupjobs.com

### Non-existing account
GET {{base_url}}/accounts/by_email?email=test@0@algeriastartupjobs.com

###
POST {{base_url}}/posts
Content-Type: application/json

{
  "poster": {
    "email": "zakman.dev+admin@gmail.com",
    "type": "Admin",
    "first_name": "Admino",
    "last_name": "Admini",
    "slug": ""
  },
  "post": {
    "title": "Admin trolling",
    "short_description": "",
    "description": "",
    "slug": "",
    "poster_id": 0,
    "tag_ids": [],
    "is_confirmed": false
  }
}

###
POST {{base_url}}/posts
Content-Type: application/json

{
  "poster": {
    "email": "zakman.dev+strawhats@gmail.com",
    "type": "Company",
    "company_name": "Strawhats LLC",
    "slug": ""
  },
  "post": {
    "title": "Experienced Shipwright",
    "short_description": "",
    "description": "",
    "slug": "",
    "poster_id": 0,
    "tag_ids": [],
    "is_confirmed": false
  }
}

###
POST {{base_url}}/posts
Content-Type: application/json

{
  "poster": {
    "email": "zakman.dev+luffys@gmail.com",
    "type": "Individual",
    "first_name": "Monkey",
    "last_name": "De Luffy",
    "slug": ""
  },
  "post": {
    "title": "Master Chef",
    "short_description": "",
    "description": "",
    "slug": "",
    "poster_id": 0,
    "tag_ids": [],
    "is_confirmed": false
  }
}

###
POST {{base_url}}/posts/confirm
Content-Type: application/json

{
  "post_id": 203,
  "confirmation_id": "VII6BHSQVLCF",
  "confirmation_code": "BQJO"
}

### Non-existing account
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "zakman.dev+non-existant@gmail.com"
}

###
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "zakman.dev+test-1@gmail.com"
}

###
# @name confirmLogin
POST {{base_url}}/auth/confirm_login
Content-Type: application/json

{
  "email": "zakman.dev+test-1@gmail.com",
  "confirmation_id": "L4ITAFY6HFGX",
  "confirmation_code": "TS2Q"
}

###
GET {{base_url}}/accounts/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET {{base_url}}/posts/for_tag/engineer
Content-Type: application/json

###
DELETE {{base_url}}/posts/0
Content-Type: application/json
Authorization: Bearer {{auth_token}}
