# local db:
@dbBaseUrl = http://localhost:7070

# local:
@baseUrl = http://localhost:9090
# staging:
# @baseUrl = https://staging.api.algeriastartupjobs.com
# production:
# @baseUrl = http://production.api.algeriastartupjobs.com

###
POST {{baseUrl}}/test/seed
x-admin-auth-code: password123

###
POST {{baseUrl}}/test/clean
x-admin-auth-code: password123

###
GET {{dbBaseUrl}}/export
Authorization: Basic root root
NS: test
DB: test

###
POST {{dbBaseUrl}}/sql
Accept: application/json
Authorization: Basic root root
NS: test
DB: test

BEGIN TRANSACTION;

LET $count = (SELECT count() FROM account GROUP BY count)[0].count || 0;

CREATE account:{ id: $count } CONTENT {
  email: 'contact@example.com',
  slug: 'doe_llc',
  type: 'Company',
  company_name: 'Doe LLC',
};

COMMIT TRANSACTION;

###
POST {{dbBaseUrl}}/sql
Accept: application/json
Authorization: Basic root root
NS: test
DB: test

DELETE account;
DELETE post;
DELETE tag;
DELETE category;

###
POST {{dbBaseUrl}}/sql
Accept: application/json
Authorization: Basic root root
NS: test
DB: test

SELECT *, id.id as id FROM post:{ id: 100 }

###
POST {{dbBaseUrl}}/sql
Accept: application/json
Authorization: Basic root root
NS: test
DB: test

SELECT slug, title, poster_id, short_description, category_id, tag_ids, id.id as id FROM post WHERE true LIMIT 10 START 0

###
POST {{dbBaseUrl}}/sql
Accept: application/json
Authorization: Basic root root
NS: test
DB: test

SELECT name, slug, id.id as id FROM tag WHERE array::any([id.id=10, id.id=11]) LIMIT 10 START 0

###
POST {{dbBaseUrl}}/sql
Accept: application/json
Authorization: Basic root root
NS: test
DB: test

LET $tag_ids = (SELECT tag_ids FROM post:{ id: 100 }).tag_ids;
SELECT title, tag_ids, id.id as id FROM post WHERE $tag_ids ANYINSIDE tag_ids LIMIT 10 START 0

